config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :skip => [:registrations]
  as :user do
      get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
      patch 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :images
  get 'biographies/reset_featured' => "biographies#reset_featured"
  get 'biographies/check_links' => "biographies#check_links"
  resources :biographies
  resources :authors, except: [:show]
  get 'comments/approve/(:approve_key)' => "comments#approve", :as => 'approve_comment'
  resources :comments
  get 'home' => "static_content#home"
  resources :static_content, except: [:index], path: "/", param: :slug
  root :to => redirect('/home')
end

app/models/biography.rb
class Biography < ApplicationRecord
    include ApplicationHelper
    has_many :images
    has_many :comments
    validates :slug, presence: true, uniqueness: true
    validates :title, presence: true
    validates :body, presence: true
    default_scope { order(title: :asc) }
    before_save :clean_bio_urls
    before_save :clean_bio_html

    has_many :biography_authors
    accepts_nested_attributes_for :biography_authors, reject_if: :all_blank, allow_destroy: true

    #has_many :authors, :through => :biography_authors

    belongs_to :primary_country, foreign_key: :primary_country_id, class_name:"Country", optional: true
    belongs_to :secondary_country, foreign_key: :secondary_country_id, class_name:"Country", optional: true

    def approved_comments
       comments.where(approved: true).order(:created_at)
    end

    def body_with_images
        output = ""
        images = generate_image_tags
        p_counter = 0
        get_body_elements.each do |element, index|
            output += element.to_html
            if element.text.length > 200
                p_counter += 1
                output += insert_image(p_counter, images)
            end
        end
        output
    end

    def has_single_author
        biography_authors.length <= 1 ? true : false
    end

    def other_author (author)
        if not has_single_author
            biography_authors.where.not(author_id: author.id).first.author
        end
    end

    def parse_links (links)
        parsed_links = Array.new
        links.each do |link|
          parsed_links.push({title: link.inner_html, url: link['href'], bio: self})
        end
        parsed_links
    end


    def gather_links
        links = Nokogiri::HTML::fragment(self.external_links).children.css('a')
        links += Nokogiri::HTML::fragment(self.references).children.css('a')
        parse_links(links)
    end

private

    def clean_bio_urls
        clean_urls(self.body)
    end

    def clean_bio_html
        self.body = clean_html(self.body)
        self.references = clean_html(self.references)
        self.external_links = clean_html(self.external_links)
    end

    def insert_image(p, images)
        images.each do |img|
            if img["after_para"] == p
                return img["tag"]
            end
        end
        return String.new
    end

    def get_body_elements
        Nokogiri::HTML::fragment(self.body).children
    end

    def generate_image_tags
        tags = []
        after_para = 1
        class_left = "float-sm-left mr-sm-3"
        class_right = "float-sm-right ml-sm-3"
        self.images.order(:id).each do |image|
            pos_class = ApplicationController.helpers.cycle(class_right, class_left, name: "pos_class" )
            tag = ApplicationController.render(partial: 'images/tag', assigns: {img: image, class: pos_class})
            tags.push({"tag"=>tag, "after_para"=>after_para})
            after_para += 2
        end
        ApplicationController.helpers.reset_cycle("pos_class")
        tags
    end

end

app/controllers/biographies_controller.rb
class BiographiesController < ApplicationController
    include BiographiesHelper
    before_action :authenticate_user!, :only => [:new, :create, :edit, :update, :destroy, :reset_featured, :check_links]

    def show
        @biography = Biography.find_by(slug: params[:id]) || Biography.find(params[:id])
    end

    def index
        @biographies = if params[:search]
            Biography.where('title ILIKE ?', "%#{params[:search]}%").page params[:page]
        else
            Biography.all.page params[:page]
        end
    end

    def new
        @biography = Biography.new
    end

    def create
        @biography = Biography.new( biography_params )
        begin
            if @biography.save
                redirect_to biography_path(@biography.slug)
            else
                render 'new'
            end
        rescue ActiveRecord::RecordNotUnique
            @biography.errors.add(:base,'Attributed author and author position must be unique.')
            render 'new'
        end
    end

    def edit
        @biography = Biography.find_by(slug: params[:id]) || Biography.find(params[:id])
    end

    def update
        @biography = Biography.find_by(slug: params[:id]) || Biography.find(params[:id])
        @biography.assign_attributes(biography_params)
        begin
            if @biography.save
                redirect_to biography_path(@biography.slug)
            else
                render 'edit'
            end
        rescue ActiveRecord::RecordNotUnique
            @biography.errors.add(:base,'Attributed author and author position must be unique.')
            render 'edit'
        end
    end

    def destroy
        @biography = Biography.find_by(slug: params[:id]) || Biography.find(params[:id])
        @biography.destroy
        redirect_to biographies_path
    end

    def reset_featured
        reset_featured_bios
        redirect_to "/home", :flash => { :notice => "Featured biographies reset successful" }
    end

    def check_links
        links_result = check_links_in_bios
        @fails = links_result[:fails]
        @count = links_result[:count]
    end

    private

        def biography_params
            params.require(:biography).permit(:title, :body, :slug, :authors, :lifespan,
                                                :revisions, :primary_country_id, :secondary_country_id, :south_georgia, :featured,
                                                :external_links, :references,
                                                biography_authors_attributes: [:id, :author_position, :author_id, :_destroy ])
        end

end

app/helpers/biographies_helper.rb
module BiographiesHelper

    def clear_featured
        Biography.update_all featured: false
    end

    def with_images(bios)
        bios.unscoped.joins(:images).distinct
    end

    def with_lifespan_author(bios)
        bios.where("lifespan IS NOT NULL").where("authors IS NOT NULL")
    end

    def with_first_image_orientated(bios, orientation)
      portrait_ids = []
      bios.each do |bio|
        if orientation == bio.images.order(:id).first.orientation
          portrait_ids << bio.id
        end
      end
      portrait_ids
    end

    def get_random_ids(portrait_ids, count)
        return portrait_ids.sample(count)
    end

    def get_features(ids)
        Biography.where(id: ids)
    end

    def set_featured(bios)
        bios.update_all featured: true
    end

    def reset_featured_bios
        Biography.update_all featured: false
        bios = with_images(Biography.all)
        bios = with_lifespan_author(bios)
        portrait_ids = with_first_image_orientated(bios, "portrait")
        bios_ids = get_random_ids(portrait_ids, 6)
        bios = get_features(bios_ids)
        set_featured(bios)
    end

    def gather_all_links
        links = Array.new
        Biography.all.each do |bio|
          bio.gather_links.each do |link|
            if link[:url].start_with?('https://www.youtube.com')
              link[:youtube_url] = "https://www.youtube.com/oembed?url=" + link[:url] + "&format=json"
            end
            links << link
          end
        end
        links
    end

    def check_links_in_bios
      user_agent = "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0"
      fails = Array.new
      hydra = Typhoeus::Hydra.new(max_concurrency: 20)
      links = gather_all_links
      links.each do |link|
        url = link.key?(:youtube_url) ? link[:youtube_url] : link[:url]
        request = Typhoeus::Request.new(url, method: :get, followlocation: true, timeout: 30, ssl_verifypeer: false, headers: {"User-Agent" => user_agent})
        request.on_complete do |response|
          if response.code == 0 or response.code > 308
            fails.push(link)
          end
        end
        request.on_body do |chunk|
            :abort
        end
        hydra.queue(request)
      end
      hydra.run
      {count:links.length, fails:fails}
    end

    def links_report
      links_result = check_links_in_bios
      LinksReportMailer.links_report_email(links_result[:fails], links_result[:count]).deliver_now
    end

end

app/views/biographies/_authors.html.erb
<!-- Authors modal -->
<div id="authors-info" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title">Authors</h4>
            <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        <div class="modal-body">
        <% @biography.biography_authors.each do |biography_author| %>
            <%= tag.h4( tag.strong(biography_author.author.name) ) %>
            <% if biography_author.author.biography %>
                <%= tag.p( biography_author.author.biography ) %>
            <% end %>
            <small><ul>
            <% biography_author.author.biographys.take(3).each do |biography| %>
                <li>
                    <%= link_to biography.title, biography_path(biography.slug) %>
                    <% if not biography.has_single_author %>
                        <ul>
                            <li>with
                                <%= link_to biography.other_author(biography_author.author).name,
                                    "#{authors_path}##{biography.other_author(biography_author.author).simple_slug}",
                                    class: "font-italic"  
                                %>
                            </li>
                        </ul>
                    <% end %>
                </li>
            <% end %>
            <% if biography_author.author.biographys.length > 3 %>
                <li class="more-link"><%= link_to "more...", "#{authors_path}##{biography_author.author.simple_slug}", class:"more-link" %></li>
            <% end %>
            </ul></small>
            <% if(biography_author != @biography.biography_authors.last) %>
                <hr>
            <% end %>
        <% end %>
        </div>
        </div>

    </div>
</div>

app/views/biographies/_biography_author_fields.erb
<div class="row nested-fields">
    <div class="col-sm-6"></div>
    <%= f.collection_select :author_id, Author.all, :id, :name, {include_blank: true},
            { class: 'col-sm-4 form-control' } %>
    <%= f.input_field :author_position,
            class: 'col-sm-1 form-control' %>
    <div class="col-sm-1 small">
        <%= link_to_remove_association '<i class="fa fa-minus"></i>'.html_safe, f, class:"btn btn-sm btn-danger" %>
    </div>
</div>

app/views/biographies/_featured.html.erb
<a href="<%= biography_path(biography.slug) %>">
    <% if biography.images.present? %>
        <img src="<%= biography.images.order(:id).first.image.url(:medium) %>" alt="..." class="card-img-top">
    <% end %>
    <div class="card-body">
        <h5 class="card-title"><strong><%= biography.title %></strong></h5>
        <p class="card-text">
            <%= truncate_html(biography.body, :length => 100 ) %>
        </p>
    </div>
</a>

app/views/biographies/_form.html.erb
<%= simple_form_for @biography, url: url, method: method, html: { class: 'form-horizontal' } do |f| %>
    <br>

    <% if @biography.errors.any? %>
        <div class="panel panel-warning">
            <div class="panel-heading"><%= pluralize(@biography.errors.count, "error") %> prohibited this article from being saved</div>
            <div class="panel-body">
                <ul>
                <% @biography.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
                </ul>
            </div>
        </div>
    <% end %>

    <div class="row">
        <%= f.label :title, 'Subject name',
                class: 'col-sm-2 small control-label' %>
        <%= f.input_field :title,
                placeholder: 'e.g. ABBOTT, JACK (required)',
                class: 'col-sm-7 form-control' %>
        <%= f.label :featured, 'Featured',
                class: 'col-sm-2 small control-label' %>
        <%= f.input_field :featured,
                class: 'col-sm-1 small form-control' %>
    </div>
    <div class="row">
        <%= f.label :lifespan, 'Lifespan',
                class: 'col-sm-2 small control-label' %>
        <%= f.input_field :lifespan,
                placeholder: "e.g. 1921-1987",
                class: 'col-sm-3 form-control' %>
        <%= f.label :slug, 'Slug',
                    class: 'col-sm-2 small control-label' %>
        <%= f.input_field :slug,
                placeholder: "e.g. abbot_jack (required)",
                class: 'col-sm-5 form-control' %>
    </div>
    <hr>
    <div class="row">
        <%= f.label :primary_country, '1st Country',
                class: 'col-sm-2 small control-label' %>
        <%= f.collection_select :primary_country_id, Country.all, :id, :name, {prompt:'Select country'},
                { class: 'col-sm-2 form-control' } %>
        <%= f.label :secondary_country, '2nd Country',
                class: 'col-sm-2 small control-label' %>
        <%= f.collection_select :secondary_country_id, Country.all, :id, :name, {prompt:'Optional'},
                { class: 'col-sm-2 form-control' } %>
        <div class="col-sm-1"></div>
        <%= f.label :south_georgia, 'S. Georgia',
                class: 'col-sm-2 small control-label' %>
        <%= f.input_field :south_georgia,
                class: 'col-sm-1 small form-control' %>
    </div>
    <hr>
    <div class="row">
    <%= f.label :authors, 'Authors',
            class: 'col-sm-2 small control-label' %>
    <%= f.input_field :authors,
            placeholder: 'e.g. Andrew David & Carlos Novi',
            class: 'col-sm-10 form-control' %>
    </div>
    <div class="row">
        <div class="col-sm-6"></div>
        <div class="col-sm-4 text-right"><small>Attributed author</small></div>
        <div class="col-sm-1"><small>Position</small></div>
    </div>
    <div id="nested-authors">
        <%= f.simple_fields_for :biography_authors do |biography_author| %>
            <%= render 'biography_author_fields', f: biography_author %>
        <% end %>

    </div>
    <%= link_to_add_association 'Add author', f, :biography_authors,
            class:'small pull-right',
            data:{"association-insertion-method": 'after',
                  "association-insertion-node": '#nested-authors'} %>

    <%= f.input :body, as: :summernote,
            required: false %> 

    <%= f.input :external_links, as: :summernote,
            required: false %>

    <%= f.input :references, as: :summernote,
            required: false %>
    
    
    <%= f.input :revisions %>
    <div class="form-actions">
        <%= link_to "Back", biographies_path, class: "btn btn-outline-dark", role:"button" %>
        <%= f.button :submit, class: "btn btn-outline-dark" %>
    </div>
<% end %>

app/views/biographies/_search.html.erb
<div class="my-5 col-xl-8 offset-xl-2">
    <%= form_tag biographies_path, :method => 'get' do %>
        <div class="input-group" class="width">
            <%= text_field_tag 'search', params[:search], placeholder: "Search biographies", class: "form-control form-control-lg" %>
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="submit"><i class="fa fa-search"></i></button>
            </div>
        </div>
    <% end %>
</div>

app/views/biographies/check_links.erb
<h3>
    <strong>Links Report</strong>
    <small></small>
</h3>

<h4><strong>Report of links has been completed.</strong></h4>
<p>
  Links scanned: <%= @count %>
  <br>
  Links failed: <%= @fails.length %>
</p>

<% if @fails.length > 0 %>
    <h4><strong>Failures</strong></h4>
    <dl>
    <%  @fails.each do |fail| %>
      <dt><%= link_to fail[:bio].title,  edit_biography_url(fail[:bio].slug), target: '_blank' %></dt>
      <dd><%= link_to fail[:title].html_safe, fail[:url], target: '_blank' %></dd>
    <% end %>
  </dl>
<% else %>
  <h4><strong>No failures</strong></h4>
<% end %>

app/views/biographies/edit.html.erb
<h4>Edit biography</h4>

<%= render partial: 'form', locals: {url: biography_path(@biography), method: :PATCH} %>

app/views/biographies/index.html.erb
<h3>
  <strong>Biographies</strong>
  <%= render partial: 'biographies/search' %>
  <% if user_signed_in? %>
      <%= link_to "New", new_biography_path, class: "btn btn-success btn-sm float-right", role:"button" %>
  <% end %>
</h3>
<table id="index" class="table">
    <% if @biographies.each do |biography| %>
    <tr>
        <td>
            <%= link_to biography.title, biography_path(biography.slug) %>
            <%= biography.lifespan %>
            <% if user_signed_in? %>
                <div class="btn-group float-right">
                    <%= link_to "Edit", edit_biography_path(biography.slug), class: "btn btn-outline-dark btn-sm", role:"button" %>
                    <%= link_to "Delete", biography_path(biography.slug),
                                            class: "btn btn-danger btn-sm",
                                            role:"button",
                                            data: {:confirm => 'Are you sure?'},
                                            method: :DELETE %>
                </div>
            <% end %>

            <br>
            <span class="small">
                <% if biography.primary_country.present? %>
                    <em>
                    <%= biography.primary_country.name + " " %>
                    <% if biography.secondary_country.present? %>
                        (also <%= biography.secondary_country.name %>)
                    <% end %>
                </em>
                <% end %>
                <% if biography.south_georgia %>
                    <%= tag.button "SG", class:"btn btn-outline-dark btn-sm ml-2 px-1", data:{toggle:"tooltip", placement:"right"}, title:"South Georgia" %>
                <% end %>
            </span>
            <%= truncate_html(biography.body, :length => 200 ) %>
        </td>
    </tr>
    <% end.empty? %>
    <tr>
        <td>No results</td>
    </tr>
  <% end %>
</table>

<%= paginate @biographies %>

app/views/biographies/new.html.erb
<h4>New biography</h4>

<%= render partial: 'form', locals: {url: biographies_path, method: :POST} %>

app/views/biographies/show.html.erb
<h3>
    <strong><%= @biography.title %></strong>
    <small></small>
</h3>

<% if user_signed_in? %>
    <p>
        <%= link_to "Back", biographies_path, class: "btn btn-outline-dark btn-sm", role:"button" %>
        <%= link_to "Edit", edit_biography_path(@biography.slug), class: "btn btn-outline-dark btn-sm", role:"button" %>
        <%= link_to "Delete", biography_path(@biography.slug), class: "btn btn-danger btn-sm", role:"button" , data: {:confirm => 'Are you sure?'}, method: :DELETE %>
    </p>
<% end %>

<h4>
<%= @biography.lifespan %>
<span class="pull-right">
    <% if @biography.primary_country.present? %>
        <em><small>
            from <%= @biography.primary_country.name + " " %>
            <% if @biography.secondary_country.present? %>
                (also <%= @biography.secondary_country.name %>)
            <% end %>
        </small></em>
    <% end %>
    <% if @biography.south_georgia %>
        <%= tag.button "SG", class:"btn btn-outline-dark btn-sm ml-3 px-1", data:{toggle:"tooltip", placement:"left"}, title:"South Georgia" %>
    <% end %>
</span>
</h4>
<br>

<%= tag.div @biography.body_with_images.html_safe, class:"biography_body" %>

<% if @biography.authors.present? %>
    <%= tag.div class:"biography_authors_wrapper row-fluid", style:"clear:both;" do%>
        <hr>
        <h4><%= tag.strong("Authors") %></h4>
        <%= tag.div class:"biography_authors ml-3 mb-2" do %>
            <%= @biography.authors %><%= '<button type="button" class="btn btn-outline-dark btn-sm ml-3" data-toggle="modal" data-target="#authors-info">Author Info</button>'.html_safe %>
        <% end %>
    <% end %>
<% end %>

<% if @biography.external_links.present? %>
    <h4><%= tag.strong("External links") %></h4>
    <%= tag.div @biography.external_links.html_safe, class:"biography_external_links ml-3 mb-2" %>
<% end %>

<% if @biography.references.present? %>
    <h4><%= tag.strong("References") %></h4>
    <%= tag.div @biography.references.html_safe, class:"biography_references ml-3 mb-2" %>
<% end %>

<h4><%= tag.strong("Comments") %></h4>
<% if @biography.approved_comments.present? %>
    <% if @biography.approved_comments.each do |comment| %>
        <%= render partial: 'comments/show_inline', locals: { comment: comment } %>
    <% end.empty? %>
    <% end %>
<% end %>
<button id="comment_button" type="button" class="btn btn-outline-dark ml-3 mb-2" data-toggle="modal" data-target="#myModal">Add comment</button>

<% if @biography.revisions.present? %>
    <h4><%= tag.strong("Revisions") %></h4>
    <%= tag.div class:"biography_revsions ml-3" do %>
        <%= simple_format @biography.revisions, class: "small" %>
    <% end %>
<% end %>

<%# Hidden content for modal popups %>

<%= render partial: 'authors', locals: {biography: @biography} %>
<%= render partial: 'comments/new', locals: { biography: @biography } %>