config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :skip => [:registrations]
  as :user do
      get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
      patch 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :images
  get 'biographies/reset_featured' => "biographies#reset_featured"
  get 'biographies/check_links' => "biographies#check_links"
  resources :biographies
  resources :authors, except: [:show]
  get 'comments/approve/(:approve_key)' => "comments#approve", :as => 'approve_comment'
  resources :comments
  get 'home' => "static_content#home"
  resources :static_content, except: [:index], path: "/", param: :slug
  root :to => redirect('/home')
end

app/models/author.rb
class Author < ApplicationRecord
    validates :last_name, presence: true, uniqueness: {scope: :first_name}
    has_many :biography_authors, :dependent => :destroy
    has_many :biographys, :through => :biography_authors
    default_scope { order(last_name: :asc, first_name: :asc) }

    def name
        first_name ? "#{first_name} #{last_name}" : last_name
    end

    def simple_slug
        name.downcase.strip.gsub(' ', '-').gsub(/[^\w-]/, '')
    end

end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
    before_action :authenticate_user!, except:[:index]

    def index
        @authors = Author.all
    end

    def new
        @author = Author.new
    end

    def create
        @author = Author.new( author_params )
        if @author.save
            redirect_to authors_path + "##{@author.simple_slug}"
        else
            render 'new'
        end
    end

    def edit
        @author = Author.find( params[:id] )
    end

    def update
        @author = Author.find( params[:id] )
        if @author.update( author_params )
            redirect_to authors_path + "##{@author.simple_slug}"
        else
            render 'edit'
        end
    end

    def destroy
        @author = Author.find( params[:id] )
        @author.destroy
        redirect_to authors_path
    end

private

    def author_params
        params.require(:author).permit(:biography, :last_name, :first_name)
    end

end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_form.html.erb
<%= simple_form_for @author, url: url, method: method do |f| %>
  <%= f.input :last_name %>
  <%= f.input :first_name %>
  <%= f.input :biography %>

  <div class="form-actions">
      <%= link_to "Back", authors_path, class: "btn btn-outline-dark", role:"button" %>
      <%= f.button :submit,  class: "btn btn-outline-dark" %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h4>Edit author</h4>

<%= render partial: 'form', locals: {url: author_path(@author), method: :PATCH} %>

app/views/authors/index.html.erb
<h3>
  <strong>Authors</strong>
  <% if user_signed_in? %>
      <%= link_to "New", new_author_path, class: "btn btn-success btn-sm float-right", role:"button" %>
  <% end %>
</h3>
<div class="card-columns custom-columns">
    <% if @authors.each do |author| %>
        <div class="card">
            <div class="card-body">
                <%= tag.span(nil, class: "anchor", id: author.simple_slug) %>
                <h5 class="card-title">
                <%= author.name %>
                <% if user_signed_in? %>
                    <%= link_to "Edit", edit_author_path(author), class: "btn btn-outline-dark btn-sm", role:"button" %>
                    <%= link_to "Delete", author_path(author), class: "btn btn-danger btn-sm", role:"button", data: {:confirm => 'Are you sure?'}, method: :DELETE %>
                <% end %>
                </h5>

                <% if author.biography %>
                    <%= tag.p( author.biography, class: "card-text" ) %>
                <% end %>
                <hr>
                <small><ul>
                <% author.biographys.each do |biography| %>
                    <li>
                        <%= link_to biography.title, biography_path(biography.slug), class: "card-link" %>
                        <% if not biography.has_single_author %>
                            <ul>
                                <li>with
                                    <%= tag.span biography.other_author(author).name,
                                        class: "card-link font-italic author-link",
                                        data:  { "hash": biography.other_author(author).simple_slug  } %>
                                </li>
                            </ul>
                        <% end %>
                    </li>
                <% end %>
                </ul></small>
            </div>
        </div>
    <% end.empty? %>
        <div class="item">
            No authors
        </div>
    <% end %>
</div>

app/views/authors/new.html.erb
<h4>New author</h4>

<%= render partial: 'form', locals: {url: authors_path, method: :POST} %>