config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :skip => [:registrations]
  as :user do
      get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
      patch 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :images
  get 'biographies/reset_featured' => "biographies#reset_featured"
  get 'biographies/check_links' => "biographies#check_links"
  resources :biographies
  resources :authors, except: [:show]
  get 'comments/approve/(:approve_key)' => "comments#approve", :as => 'approve_comment'
  resources :comments
  get 'home' => "static_content#home"
  resources :static_content, except: [:index], path: "/", param: :slug
  root :to => redirect('/home')
end

app/models/image.rb
class Image < ApplicationRecord
    include ApplicationHelper
    belongs_to :biography
    has_attached_file :image,
                    styles: {  thumb: ["100x100>", :jpg],
                               medium: ["300x300>", :jpg],
                               original: ["800x800>", :jpg]
                           },
                    default_url: "/images/:style/missing.png",
                    url: "/system/biography_images/:style/:filename",
                    path: ":rails_root/public/system/biography_images/:style/:filename"

    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
    validates_attachment_presence :image
    validates :title, presence: true
    validates :caption, presence: true
    before_save :clean_image_urls
    before_save :populate_dims

    def orientation
        if self.dim_x.nil? or self.dim_y.nil? 
            "missing"
        else 
            ratio = self.dim_x.to_f / self.dim_y.to_f
            if ratio > 0.65 and ratio <= 0.85
                "portrait"
            elsif ratio >= 1.15
                "landscape" 
            elsif ratio > 0.85 and ratio < 1.15   
                "square"
            else
                "other"
            end
        end
    end

private

    def clean_image_urls
      clean_urls(self.caption)
    end

    def populate_dims
        if self.image.queued_for_write[:original] != nil
            path = self.image.queued_for_write[:original].path
        else
            path = self.image.path(:original)
        end
        
        if File.file?(path)
            dimensions = Paperclip::Geometry.from_file(path)
            self.dim_x = dimensions.width
            self.dim_y = dimensions.height
        else
            puts "MISSING: %s" % path
        end 
    end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
    before_action :authenticate_user!

    def index
        @images = Image.all.order(:id)
    end

    def show
        @image = Image.find( params[:id] )
    end

    def new
        @image = Image.new
    end

    def edit
        @image = Image.find( params[:id] )
    end

    def create
        @image = Image.new( image_params )
        if @image.save
            redirect_to @image
        else
            render 'new'
        end
    end

    def update
        @image = Image.find( params[:id] )
        if @image.update( image_params )
            redirect_to @image
        else
            render 'edit'
        end
    end

    def destroy
        @image = Image.find( params[:id] )
        @image.destroy
        redirect_to images_path
    end

private

    def image_params
        params.require(:image).permit(:biography_id, :image, :caption, :title, :attribution)
    end

end

app/views/images/_form.html.erb
<%= simple_form_for @image, url: url, method: method do |f| %>
  <%= f.association :biography %>
  <%= f.input :title %>
  <%= f.input :caption , as: :summernote %>
  <%= f.input :attribution %>
  <% if @image.image.exists? %>
  <%= image_tag @image.image.url(:medium) %><br/>
  <% end %>
  <%= f.input :image, as: :file %>
  <div class="form-actions">
      <%= link_to "Back", images_path, class: "btn btn-outline-dark", role:"button" %>
      <%= f.button :submit , class: "btn btn-outline-dark"%>
  </div>
<% end %>

app/views/images/_tag.html.erb
<div class="figure <%=@class%> my-2 text-center float-xs-none mx-xs-auto d-block" >
        <%=
            link_to(
                image_tag( @img.image.url("medium"), class:"figure-img img-fluid rounded" ),
                @img.image.url("original"),
                data:{  footer: @img.caption.html_safe +
                                tag.div(
                                    tag.p(tag.strong(@img.id), class:"float-left mb-0") +
                                    tag.p(@img.attribution, class: "small float-right mb-0"),
                                    class:"w-100 mb-0 clearfix"
                                ),
                        toggle:'lightbox',
                        gallery:'multiimages'
                }) 
        %>
        <figcaption class="figcaption small text-sm-left">
            <%= content_tag(:b, @img.id) + " " + truncate_html(@img.caption.html_safe, :length => 40) %>
        </figcaption>
</div>

app/views/images/edit.html.erb
<h4>Edit image</h4>

<%= render partial: 'form', locals: {url: image_path(@image), method: :PATCH} %>

app/views/images/index.html.erb
<h4>
  <strong>Images</strong> <%= link_to "New", new_image_path, class: "btn btn-success btn-sm float-right", role:"button" %>
</h4>
<table id="index" class="table">
    <% if @images.each do |image| %>
    <tr>
        <td>
            <%= link_to image.title, image_path(image) %>
        </td>
        <td>
            <%= image.biography.title %>
        </td>
        <td>
            <%= image_tag image.image.url(:thumb) %>
        </td>
        <td>
            <div class="btn-group float-right">
            <%= link_to "Edit", edit_image_path(image), class: "btn btn-outline-dark btn-sm float-right", role:"button" %>
            <%= link_to "Delete", image_path(image), class: "btn btn-danger btn-sm float-right", role:"button", data: {:confirm => 'Are you sure?'}, method: :DELETE %>
            </div>
        </td>
    </tr>
    <% end.empty? %>
    <tr>
        <td>No images</td>
    </tr>
  <% end %>
</table>

app/views/images/new.html.erb
<h4>New image</h4>

<%= render partial: 'form', locals: {url: images_path, method: :POST} %>

app/views/images/show.html.erb
<table class="table">
    <tr>
        <td>Title: </td><td><strong><%= @image.title %></td>
    </tr>
    <tr>
        <td>Biography: </td><td><%= @image.biography.title %></td>
    </tr>
    <tr>
        <td>Caption: </td><td><%= @image.caption.html_safe %></td>
    </tr>
    <tr>
        <td>Attribution: </td><td><%= @image.attribution %></td>
    </tr>
    <tr>
        <td>Image: </td><td><%= image_tag @image.image.url(:medium) %></td>
    </tr>
</table>

<%= link_to "Back", images_path, class: "btn btn-outline-dark", role:"button" %>
<%= link_to "Edit", edit_image_path, class: "btn btn-outline-dark", role:"button" %>