config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :skip => [:registrations]
  as :user do
      get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
      patch 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :images
  get 'biographies/reset_featured' => "biographies#reset_featured"
  get 'biographies/check_links' => "biographies#check_links"
  resources :biographies
  resources :authors, except: [:show]
  get 'comments/approve/(:approve_key)' => "comments#approve", :as => 'approve_comment'
  resources :comments
  get 'home' => "static_content#home"
  resources :static_content, except: [:index], path: "/", param: :slug
  root :to => redirect('/home')
end

app/views/layouts/_footer.html.erb
<footer class="page-footer font-small bg-secondary">
    <div class="footer-copyright text-center py-3 text-light">
        &copy; 2012-21 David Tatham. All rights reserved.<br>
        <% if not user_signed_in? %>
            <%= link_to "Login", new_user_session_path, :class => 'small text-success'  %>
        <% end %>
    </div>
</footer>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-expand-md bg-primary navbar-dark fixed-top">
    <div class="container">
      <!-- Brand -->


      <a class="navbar-brand d-none d-lg-block" href="#">Dictionary of Falklands Biography</a>
      
      <a class="navbar-brand d-block d-sm-block d-lg-none" href="#">Falklands Biography</a>



      <!-- Toggler/collapsibe Button -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <i class="fa fa-bars"></i>
      </button>

      <!-- Menu -->
      <div class="collapse navbar-collapse  justify-content-end" id="collapsibleNavbar">
        <ul class="navbar-nav text-uppercase">

          <!--Home-->
          <li class="nav-item"><%= link_to "Home", static_content_path("home"), class: "nav-link" %></li>

          <!--Biographies-->
          <li class="nav-item"><%= link_to "Biographies", biographies_path, class: "nav-link" %></li>
          
          <!--About Menu-->
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" id="navbardrop" href="#">About</a>
            <div class="dropdown-menu shadow">
              <%= link_to "About DFB", static_content_path("about"), class:"dropdown-item" %>
              <%= link_to "The Falklands Story", static_content_path("falklands_story"), class:"dropdown-item" %>
              <%= link_to "Authors", authors_path, class:"dropdown-item" %>
              <%= link_to "Jane Cameron - Obituary", static_content_path("jane_cameron"), class:"dropdown-item" %>
              <div class="dropdown-divider"></div> 
              <%= link_to "Foreword", static_content_path("book_foreword"), class:"dropdown-item" %>
              <%= link_to "Introduction", static_content_path("book_introduction"), class:"dropdown-item" %>
              <%= link_to "Acknowledgements", static_content_path("book_acknowledgements"), class:"dropdown-item" %>
              <%= link_to "David Tatham", static_content_path("book_david_tatham"), class:"dropdown-item" %>
              <%= link_to "Reviews", static_content_path("book_reviews"), class:"dropdown-item" %>
              <%= link_to "How to buy", static_content_path("book_purchase"), class:"dropdown-item" %>
            </div>
          </li>
          
          <!--Contacts-->
          <li class="nav-item" ><%= link_to "Contacts", static_content_path("contacts"), class: "nav-link" %></li>

          <!--Admin Menu-->
          <% if user_signed_in? %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" data-toggle="dropdown" id="navbardrop" href="#">Admin</a>
                <div class="dropdown-menu shadow">
                    <%= link_to "Biographies", biographies_path, class:"dropdown-item" %>
                    <%= link_to "Images", images_path, class:"dropdown-item" %>
                    <%= link_to "Comments", comments_path, class:"dropdown-item" %>
                    <%= link_to "Reset featured", "/biographies/reset_featured", class:"dropdown-item" %>
                    <%= link_to "Check links", "/biographies/check_links", class:"dropdown-item" %>
                    <%= link_to "Create new page", new_static_content_path, class:"dropdown-item" %>
                    <div class="dropdown-divider"></div>
                    <%= link_to "Documentation", static_content_path("docs_index"), class:"dropdown-item" %>
                    <div class="dropdown-divider"></div>
                    <%= link_to "Change password", edit_user_registration_path, class:"dropdown-item" %>
                    <%= link_to "Logout", destroy_user_session_path, method: :delete, class:"dropdown-item"  %>
                </div>
            </li>
          <% end %>

        </ul>
      </div>
    </div><!--container-->
  </nav> 
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>DFB</title>
<%= render 'application/favicon' %>
<%= csrf_meta_tags %>
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <% if not user_signed_in? %>
    <%= render 'application/analytics' %>
    <% end %>
</head>
<body>

<%= render 'layouts/navbar' %>

<!-- Begin page content -->
<div class="container-flex" style="margin-top:72px">

    <% unless alert.nil? %>
        <div class="alert alert-info alert-dismissable"><%= alert %>
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        </div>
    <% end %>
    <% unless notice.nil? %>
        <div class="alert alert-warning alert-dismissable"><%= notice %>
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        </div>
    <% end %>

</div>

<%= yield :home %>
<div class="container py-3">
    <%= yield %>
</div>

<%= render 'layouts/footer' %>

</body>
</html>